### ISSUE TITLE
wiki update

### ISSUE THREAD

**Issue by leamas** [iguanaworks/iguanair-lirc#2]
Don't know how to make a pull request for the wiki. Here comes an update for the compile page:  http://paste.fedoraproject.org/418790/72149814

**Comment by leamas** [comment]
Oops... at the very end there is tira.so; should of course be iguanaIR.so.

**Comment by jdunn14** [comment]
Same as the other wiki patch ticket: I dropped the ball, please pass the patches again if they are still needed.
