### ISSUE TITLE
undefined symbol: iguanaConnect_real

### ISSUE THREAD

**Issue by pmendes** [iguanaworks/iguanair-lirc#3]
I built this however the plugin fails to load giving this error
```
-                   F--   /usr/lib64/lirc/plugins/iguanaIR.so
# Error: /usr/lib64/lirc/plugins/iguanaIR.so: undefined symbol: iguanaConnect_real
```

I did not build this your standard way, instead I dropped the files in the appropriate places in the lirc 0.9.4b source tree and added an entry for iguanaIR driver in plugins/Makefile.am. The build went without errors and a iguanaIR.so is included in the plugins. However then I get the load failure. Any ideas?

(The reason why I built it in this way is that I am using Slackware; after installing the lirc-9.4b package created with a slackbuild script, I then tried installing your package as described in your README. However there was no file /usr/doc/lirc-0.9.4b/plugindocs/plugindocs.mk. Even after I dropped this file manually from the source tree into the expected location, the build still fails; this time with `"make: *** No rule to make target '/usr/doc/lirc-0.9.4b/plugindocs//index.tmpl', needed by '/usr/doc/lirc-0.9.4b/plugindocs//var/index.html'.  Stop."`.  I found it easier to change the lirc source to include your code and compile it along with the other plugins. That worked, but evidently it fails to link some library at run time.)

**Comment by jdunn14** [comment]
I believe this has been fixed over in the main code repository.  There was a missing -liguanair if I remember correctly.  In any case, this repo is being shut down in preference to that one so I'm closing this ticket.  Please open a new ticket there if this is still a problem.

The main repo can be found at:
    https://github.com/iguanaworks/iguanair
